### ISSUE TITLE
question about Image reconstrution in paper

### ISSUE THREAD

**Issue by wadesunyang** [DandilionLau/Selfie-Friendly-Abstraction#3]
您好：
      最近我阅读了您的论文《Learning Selfie-Friendly Abstraction from Artistic Style Images》，很感兴趣，其中有几点疑问还望不吝赐教，谢谢。
     
       在Image Reconstruction中，没有太明白论文中的重建原理，您能讲一下么。

       另外，公式5
         
             1）F‘w和Fw项为什么不一样， S是第一个网络的输出，那么它和S有什么区别么，为什么他们相减？
             2）S为网络输出的梯度域的值，I为原始图像，那么 ||S-I|| 梯度域和原始图像相减的意义表示什么呢？

        看了您github上的代码，由于这部分是matlab的p文件，还是很疑惑，谢谢您。

        期待您的回复。

**Comment by DandilionLau** [comment]
Hi.

(1) We use F'w to denote the network(partial weights) for the horizontal (x-axis) gradient, while Fw is used to denote the network(partial weights) for the vertical (y-axis) gradient. Since the 6 channel gradients are concatenated in a channel-wise manner, you can think that in convolution, F'w refers to the filter weights for 3 channels, and Fw refers to the filter weights for the other 3 channels. As for implementation, you can regard all 6 channels as Fw for simplification. The original notation is from our previous paper "Deep Edge Aware Filters" in ICML 2015.

(2) Sorry for the ambiguous notation in the manuscript. The notation S should actually refer to the reconstructed RGB output (instead of gradient maps). As for the objective function (5), the first term is to ensure the color of the output to be similar to the input image, and the second term is to ensure the gradient maps of the reconstructed RGB image to be similar to the network output gradient maps, which are F'w(\partial_x I) and Fw(\partial_y I).

The reconstruction objective function can be solved by preconditioned conjugate gradient (PCG). Although the detailed steps are not included here, you can refer to the original paper for how to solve a similar objective function like the one we have:

Szeliski, Richard. Locally adapted hierarchical basis pre-conditioning. ACM Trans. Graph., 25(3):1135–1143, 2006.

**Comment by lintianwei-blog** [comment]
Hi @DandilionLau Thanks for your project! But I found it difficult to implement reconstruction part, can you provide matlab code or python code of "grad_process.p". Thanks again!
